apiVersion: v1
kind: Pod
metadata:
  name: model-checker
spec:
  volumes:
    - name: pvc-ai-lab-models
      persistentVolumeClaim:
        claimName: pvc-ai-lab-models
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/models"
          name: pvc-ai-lab-models
  initContainers:
    - name: init-model-checker
      image: busybox
      volumeMounts:
        - mountPath: "/models"
          name: pvc-ai-lab-models
      env:
        - name: MODEL_PATH
          value: "/models/hf.instructlab.granite-7b-lab-GGUF"
        - name: MODEL_SHA256
          value: "6adeaad8c048b35ea54562c55e454cc32c63118a32c7b8152cf706b290611487"
        - name: INIT_TIMEOUT
          value: "3600"  # Timeout in seconds
      command:
        - sh
        - -c
        - |
          MODEL_PATH=${MODEL_PATH}
          MODEL_SHA256=${MODEL_SHA256}
          INIT_TIMEOUT=${INIT_TIMEOUT}

          start_time=$(date +%s)

          while true; do
              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))

              if [ $elapsed_time -ge $INIT_TIMEOUT ]; then
                  echo "Init container timeout after ${INIT_TIMEOUT} seconds"
                  exit 1
              fi

              if [ -f "$MODEL_PATH" ]; then
                  calculated_hash=$(sha256sum "$MODEL_PATH" | awk '{ print $1 }')
                  if [ "$calculated_hash" = "$MODEL_SHA256" ]; then
                      echo "SHA256 hash matches"
                      exit 0
                  fi
              fi

              echo "SHA256 hash does not match. Expected: ${MODEL_SHA256}, Received: ${calculated_hash}"
              sleep 5
          done
